#!/usr/bin/env bash
# Repeatable from-source llama.cpp (server) build for the DGX Spark (GB10 / sm_121a).
#
# Resolves and records the exact CUDA base-image digest and llama.cpp commit,
# then builds the image tagged with the short commit (plus :latest). Re-running
# with the same build.lock reproduces the same image.
#
# Usage:
#   ./build.sh                          # build from current llama.cpp master HEAD
#   ./build.sh --ref b9671              # build a specific tag/branch/commit
#   ./build.sh --refresh-base          # re-pull the CUDA base, re-pin its digest
#   ./build.sh --no-cache              # force a clean rebuild
#   ./build.sh --reproduce             # rebuild exactly what build.lock records
#   ./build.sh --no-ui                 # build the server without the embedded Web UI
set -euo pipefail
cd "$(dirname "$0")"

CUDA_VERSION="13.0.3"
UBUNTU_VERSION="ubuntu24.04"
BASE_REPO="nvidia/cuda:${CUDA_VERSION}-devel-${UBUNTU_VERSION}"
LLAMA_REPO="https://github.com/ggml-org/llama.cpp.git"
IMAGE_NAME="llama-spark"
CUDA_ARCH="121a"

LLAMA_REF="master"
REFRESH_BASE=0
NO_CACHE=""
REPRODUCE=0
BUILD_UI="ON"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --ref)           LLAMA_REF="$2"; shift 2 ;;
    --refresh-base)  REFRESH_BASE=1; shift ;;
    --no-cache)      NO_CACHE="--no-cache"; shift ;;
    --reproduce)     REPRODUCE=1; shift ;;
    --no-ui)         BUILD_UI="OFF"; shift ;;
    -h|--help)       sed -n '2,13p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

export DOCKER_BUILDKIT=1

# --- 1. resolve the base image digest (pin) --------------------------------
if [[ "$REPRODUCE" == 1 && -f build.lock ]]; then
  # shellcheck disable=SC1091
  source build.lock
  echo ">> reproducing build.lock: base=$BASE_DIGEST llama=$LLAMA_COMMIT"
else
  if [[ "$REFRESH_BASE" == 1 ]] || ! docker image inspect "$BASE_REPO" >/dev/null 2>&1; then
    echo ">> pulling base image $BASE_REPO ..."
    docker pull "$BASE_REPO"
  fi
  BASE_DIGEST="$(docker inspect --format '{{index .RepoDigests 0}}' "$BASE_REPO")"

  # --- 2. resolve the llama.cpp commit to build -------------------------
  if [[ "$LLAMA_REF" =~ ^[0-9a-f]{40}$ ]]; then
    LLAMA_COMMIT="$LLAMA_REF"
  else
    echo ">> resolving llama.cpp ref '$LLAMA_REF' ..."
    LLAMA_COMMIT="$(git ls-remote "$LLAMA_REPO" "$LLAMA_REF" "refs/tags/$LLAMA_REF" "refs/heads/$LLAMA_REF" \
                    | head -n1 | cut -f1)"
    [[ -z "$LLAMA_COMMIT" ]] && { echo "could not resolve '$LLAMA_REF'" >&2; exit 1; }
  fi
fi

SHORT="${LLAMA_COMMIT:0:8}"
TAG="${IMAGE_NAME}:${SHORT}"

echo "============================================================"
echo "  base image : $BASE_DIGEST"
echo "  llama ref  : $LLAMA_REF -> $LLAMA_COMMIT"
echo "  gpu arch   : $CUDA_ARCH (sm_121a / GB10)"
echo "  web ui     : $BUILD_UI"
echo "  image tags : $TAG , ${IMAGE_NAME}:latest"
echo "============================================================"

# --- 3. build --------------------------------------------------------------
# BASE_DIGEST is the full "repo@sha256:..."; split out CUDA_VERSION/UBUNTU_VERSION
# args too so the runtime stage pulls the matching -runtime image.
docker build $NO_CACHE \
  --build-arg "CUDA_VERSION=${CUDA_VERSION}" \
  --build-arg "UBUNTU_VERSION=${UBUNTU_VERSION}" \
  --build-arg "LLAMA_REPO=${LLAMA_REPO}" \
  --build-arg "LLAMA_REF=${LLAMA_COMMIT}" \
  --build-arg "CUDA_ARCH=${CUDA_ARCH}" \
  --build-arg "LLAMA_BUILD_UI=${BUILD_UI}" \
  -t "$TAG" -t "${IMAGE_NAME}:latest" \
  .

# --- 4. record provenance --------------------------------------------------
cat > build.lock <<EOF
# Generated by build.sh -- pins for a reproducible rebuild (./build.sh --reproduce)
BASE_DIGEST="$BASE_DIGEST"
LLAMA_REF="$LLAMA_REF"
LLAMA_COMMIT="$LLAMA_COMMIT"
CUDA_ARCH="$CUDA_ARCH"
BUILD_UI="$BUILD_UI"
EOF

echo ">> done. Built $TAG"
echo ">> serve with:  ./run.sh <hf-repo-or-local-gguf>"
